### ISSUE TITLE
Help configuring light time

### ISSUE THREAD

**Issue by jcandres** [Jay7c/jc.godot3.time-of-day#2]
I've been playing a bit with the plugin and I'm thoroughly impressed with it.

However I haven't been able to configure it to get more than 12 hours of light in a day. I've been playing with all parameters but it seems that the sun sky always dies earlier than it's supposed to. It'll hit the horizon line way before the skydome sun, resulting in some time of total darkness until the moon light kicks in. The effect is like Magritte's _The Empire of Light_.

Here's what I have at the moment:
![imagen](https://user-images.githubusercontent.com/7023706/177036554-dc737ec2-fe13-4d9e-b13e-ab86382eaa7c.png)
Here's a quick photoedit with what I'd expect in terms of light direction and intensity:
![imagen](https://user-images.githubusercontent.com/7023706/177036662-7512ebcb-a984-45d7-b587-42be66d9184a.png)

Any ideas on how to achieve this? Thank you.

**Comment by Jay7c** [comment]
> 

- Use a curve to solve this problem
![EnergyCurve](https://user-images.githubusercontent.com/75779389/177244594-4b8018bb-396f-4ddf-867e-69a6cd519ad4.png)

- It's also possible to use a gradient for ambient light
![Grad](https://user-images.githubusercontent.com/75779389/177244727-59df5b52-f8d4-42c8-b25c-b26907b26965.png)
t

Sorry to reply late.
